stages:
  - lint_test_coverage
  - build

variables:
  REPOSITORY_URL: "733623710918.dkr.ecr.us-east-1.amazonaws.com/verbose-equals-true"

build:
  stage: build
  image: docker:latest
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - echo "login to ecr"
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - echo "Running build script"
    - echo $REPOSITORY_URL
  tags:
    - local

test:
  except:
    - build
  services:
    - postgres:latest
  image: python:3.6
  stage: lint_test_coverage
  variables:
    POSTGRES_DB: "postgres"
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DJANGO_SETTINGS_MODULE: "backend.settings-gitlab-ci"
  script:
    - cd backend && pip install -r requirements.txt
    - flake8
    - pytest --cov


test_unit:
  except:
    - build
  stage: lint_test_coverage
  image: node:10.14.2-jessie
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm run test:unit

test_e2e:
  except:
    - build
  image: cypress/base:10
  stage: lint_test_coverage
  script:
    - cd frontend
    - npm install
    - apt install httping
    - npm run serve &
    - while ! httping -qc1 http://localhost:8080/login ; do sleep 1 ; done
    - $(npm bin)/cypress run
